application: FashionAudience
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- remote_api: on

handlers:
- url: /js
  static_dir: js
- url: /.*
  script: main.app

libraries:
- name: django
  version: "1.2"
- name: webapp2
  version: "2.5.2"
- name: lxml
  version: "latest"